### ISSUE TITLE
erc20 decimal support ? (crev review)

### ISSUE THREAD

**Issue by clevinson** [confio/cosmwasm-examples#26]
While performing a crev review for the cw-erc20 crate, I found the code for this contract to be clean, readable, and straightforward.

However, I was confused by the `decimals` constant state variable, which is initialized, but never used in the `parse_u128()` function for parsing amounts. My assumption is that the presence of `decimals` in the Constants struct is meant to allow for fixed point decimal math, but I can't see that implementation anywhere.

Is there supposed to be some handling of decimal math conversion in the `parse_u128` implementation?

**Comment by webmaster128** [comment]
All amounts in the contract are represented in atomic units (which you can think of Cents for Dollar or Satoshi in BTC). All math is done on atomics.

Now when the user interface needs to display an amount like 7362498276345 (decimals=10, symbol=FOO), it used those 3 ingredients to show `736.2498276345 FOO`.

Why work on atomics? Well, because fixed point math is hard to get right. You cannot use floating point primitives you get from the programming languages but need specific classes. The mathematical operations are done differently and things like multiplication or division might not be defined at all or under striong limitations. Instead we work on unsigned integers, where everything is nice, simple and native.

**Comment by clevinson** [comment]
Thanks for the reply. I understand in principle why one would work with atomic math. However, I was under the impression that since the `&str` argument in `parse_u128` is called "decimal", it was intended behavior to parse a string representation of decimals and convert it to the underlying atomic u128 integer, with the appropriate decimals offset from the token's settings.

```rust
pub fn parse_u128(decimal: &str) -> Result<u128> {
    match decimal.parse::<u128>() {
        Ok(value) => Ok(value),
        Err(_) => ContractErr {
            msg: "Error while parsing decimal string to u128",
        }
        .fail(),
    }
}
```

For what I expected, the `parse_u128` function would have to also take the token's decimals setting as an argument, (e.g. `parse_u128_with_decimals("2.34",10) => 23400000000`).

But it sounds like I may actually have an incorrect understanding of the API for this token, and that valid messages require that token values be atomic integers formatted as strings. Feel free to close this issue if that is the case.

**Comment by webmaster128** [comment]
Thanks for the follow-up information. This is an interesting problem caused by two different meanings of the English word "decimal":
1. [decadic](https://en.wiktionary.org/wiki/decadic), i.e. number expressed in digits from 0 to 9 
2. decimal number with whole number part and fractional part separated by a decimal point

When I wrote the code, I thought of the first meaning. I'll update the argument name to make it unambiguous.
